
# ------------------------------
# workflow config
# ------------------------------
workflow:
  stage: process # options: prepare, process, all

project:
  name: rfa1_v0_hpc
  output_dir: /Users/masoomeshafiee/Projects/pooled_ppi/pooled-ppi/data/rfa1_v0_hpc_output

# ----------------------------
# 1. Pooling configs
# ----------------------------

mode: one_vs_all  # one_vs_all: one bait vs all preys; many pools, each with the same bait but different subsets of preys.
                  # all_vs_all: all pairs of protein protein interactions.
approach: probabilistic # probabilistic/randomized/deterministic

input:
  fasta_path: /Users/masoomeshafiee/Projects/pooled_ppi/pooled-ppi/data/rfa1_v0.fasta
  target_id: RFA1 # for one-vs-all, set this to the bait of interest. For all-vs-all, this is ignored.
  pools_tsv: /Users/masoomeshafiee/Projects/pooled_ppi/pooled-ppi/data/rfa1_v0_hpc_output/rfa1_v0_hpc/pools.tsv # if you wanna run the json preparation separately, set this to the pools tsv generated by the pooling module

output:
  json_dir: /Users/masoomeshafiee/Projects/pooled_ppi/pooled-ppi/data/rfa1_v0_hpc_output/rfa1_v0_hpc/alphafold3_jsons # if you wanna run the json preparation separately, set this to the directory where you want the jsons to be written

pooling:
  max_pool_size: 3000 # in the futrue we will support genome-wide pooling.
  n_replicates: 1 # if set to 1, each prey only appears in one pool. If set to 2, each prey appears in two pools, etc.
                  # NOTE: for the deterministic approach, number of replicates should be set to 1.
  seed: 42
  max_protein_size: null
  weighting: length
  shuffle_ties: true

# -----------------------------
# 2. AlphaFold3 input preparation configs
# -----------------------------

alphafold3:
  model_seeds: [1]
  dialect: alfafold3 # options: alphafoldserver, alphafold3 (hpc installation)
  version: 4 # last version for HPC. For AF server, this is ignored since they always run the latest version, set to 1. 
  use_structure_template: true
  count: 1

json_preparation_options:
  overwrite: true


# -----------------------------
# 3. AlphaFold3 input validation configs
# -----------------------------

validation:
  json_dir: /Users/masoomeshafiee/Projects/pooled_ppi/pooled-ppi/data/rfa1_v0_hpc_output/rfa1_v0_hpc/alphafold3_jsons # if run validation module separately, set this to the directory containing the jsons to validate
  chain_mapping_tsv: /Users/masoomeshafiee/Projects/pooled_ppi/pooled-ppi/data/rfa1_v0_hpc_output/rfa1_v0_hpc/pool_chain_mapping.tsv # if run validation module separately, set this to the chain mapping tsv to use for validation
  max_pool_size: 3000


# -----------------------------------------------------------------
# Manual work: run AlphaFold3 server or local installation with the prepared jsons
# -----------------------------
# after running the alphaFold3 predictions, you can use the following configs to extract scores and apply size correction.
prediction:
  predictions_dir: /Users/masoomeshafiee/Projects/pooled_ppi/pooled-ppi/data/rfa1_v0_hpc_output/rfa1_v0_hpc/alphafold3_predictions # set this to the directory containing the AF3 predictions, which should be organized in subdirectories for each pool, and within those, subdirectories for each model seed, e.g. pool_1/model_seed_1/, pool_1/model_seed_2/, etc.

# -----------------------------
# 4. AlphaFold3 score extraction configs
# -----------------------------

extraction_options:
  use_top_ranked_only: true
  include_self_pairs: false
# -----------------------------
# 5. Size correction configs
# -----------------------------

size_correction:
  score_column: chain_pair_iptm

  # Options:
  # pooled_ppi_fixed = use pooled-ppi approximate coefficients
  # fit_from_data = fit coefficients from your data
  method: fit_from_data

  root_to_use: 0.5
  type_of_correction: subtract


  fixed_intercept: 0.04
  fixed_slope: 0.0044

aggregation:
  resolve_replicates: mean



